<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Version>0.9.10</Version>
    <AssemblyVersion>0.9.10.0</AssemblyVersion>
    <FileVersion>0.9.10.0</FileVersion>
    <InformationalVersion>0.9.10-preview</InformationalVersion>
  </PropertyGroup>
</Project>
